name: Humble Workflow

on:
  - pull_request
  - push

jobs:
  build-ros2-humble:
    runs-on: ubuntu-22.04
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-desktop-latest
    steps:
      - name: Build Environment
        uses: ros-tooling/setup-ros@v0.5
        with:
          required-ros-distributions: humble
      - name: Run Tests
        id: humble_action_ros_ci_step
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: decanstructor2
          target-ros2-distro: humble
      - name: Upload logs
        uses: actions/upload-artifact@v1
        with:
          name: colcon-logs-humble
          path: ${{ steps.humble_action_ros_ci_step.outputs.ros-workspace-directory-name }}/log
        if: always()
