name: Iron Workflow

on:
  - pull_request
  - push

jobs:
  build-ros2-iron:
    runs-on: ubuntu-22.04
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-iron-desktop-latest
    steps:
      - name: Build Environment
        uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: iron
      - name: Run Tests
        id: iron_action_ros_ci_step
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: decanstructor2
          target-ros2-distro: iron
      - name: Upload logs
        uses: actions/upload-artifact@v1
        with:
          name: colcon-logs-iron
          path: ${{ steps.iron_action_ros_ci_step.outputs.ros-workspace-directory-name }}/log
        if: always()
